train:
    max_epoch: 3
    max_batches: 1000
    batch_size: 16
    seed: 123456
    write_graph: False
    log_interval: 10
    eval_interval: 100
    resume_file: null  # like "data/trainer.gz"
    # resume_file: "data/trainer.gz"
    trained_file: "data/trainer.gz"
    save_on_exit: True
    eval:
        max_batches: 50

model:
    transformer:
        params_encoder:
            nhead: 8
            num_layers: 3
        params_decoder:
            nhead: 8
            num_layers: 3
            add_noise: True
            warmup_steps: 2000
            # warmup_steps: 1   # for debugging

eval:
    seed: 123456
    trained_file: "data/trainer.gz"
    save_in_last: False
