services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.gpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $pj_name.app
    container_name: $pj_name.app
    tty: true
    init: true
    privileged: true
    # network_mode: "host"  # for X / chrome browser to visible
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, video]
    volumes:
      - .:/home/$user_name/workspace
      # for chrome driver
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ~/.Xauthority:/home/$user_name/.Xauthority
      - /run/user/1000/bus:/run/user/1000/bus
      - /run/snapd.socket:/run/snapd.socket
    working_dir: /home/$user_name/workspace
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=localhost:10.0
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    # sysctls:
    #   - net.core.somaxconn=$somaxconn
    #   - net.ipv4.tcp_syncookies=0
    ports:
      - "3006:3006"     # for Streamsync
      - "7860:7860"     # gradio
      - "8501:8501"     # streamlit
      - "5000:5000"     # MLflow
    #   - "5656:5656"   # sqlite-web
    #   - "6006:6006"   # tensorboard
    #   - "8000:8000"   # webapi
    #   - "8080:8080"   # vue
    #   - "9229:9229"   # node debugger

