services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.cpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $pj_name.app
    container_name: $pj_name.app
    tty: true
    init: true
    privileged: true
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///./data/langflow.db
    ports:
      - "17860:7860"     # gradio/langflow
    command: >
      python -m langflow run --host=0.0.0.0

