FROM ubuntu:22.04

LABEL maintainer="tkosht <takehito.oshita.business@gmail.com>"

ENV TZ Asia/Tokyo
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y \
    && apt-get --fix-missing install -y sudo build-essential autoconf cmake \
        vim tmux tzdata locales dialog git openssh-server bash-completion \
        jq sqlite3 curl nodejs npm default-jre unzip \
        libgeos-dev libsnappy-dev fontconfig fonts-ipaexfont fonts-ipafont \
        libopenmpi-dev \
        postgresql postgresql-contrib \
        tesseract-ocr tesseract-ocr-jpn libtesseract-dev libleptonica-dev tesseract-ocr-script-jpan tesseract-ocr-script-jpan-vert \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

# for google-chrome
# # driver and chrome browser
RUN apt-get install -y libgbm-dev x11vnc xvfb fonts-noto-color-emoji \
    && CHROMEDRIVER_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE) \
    && curl -sSL -o /tmp/chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip \
    && cd /tmp && unzip chromedriver-linux64.zip && mv chromedriver-linux64/chromedriver /usr/local/bin/ \
    && curl -sSL -o /tmp/chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chrome-linux64.zip \
    && cd /tmp && unzip chrome-linux64.zip && mv chrome-linux64 /opt \
    && fc-cache -f -v

ENV PATH $PATH:/opt/chrome-linux64

RUN apt-get --fix-missing install -y --no-install-recommends \
        python3.10 \
        python3.10-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel

RUN ln -s /usr/bin/python3.10 /usr/bin/python \
    && ln -s /usr/bin/pdb3 /usr/bin/pdb

ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8" \
    TZ="Asia/Tokyo" \
    TERM="xterm"


RUN python -m pip install --upgrade pip
RUN python -m pip install -U \
    langflow langfuse \
    langchain langchain-experimental \
    dify-client ragas

# upgrade system
RUN apt-get upgrade -y \
    && apt-get autoremove -y \
    && apt-get clean -y
    # && rm -rf /var/lib/apt/lists/*

# setup general user
ARG user_id=1000
ARG group_id=1000
ARG user_name
ARG group_name

RUN groupadd --gid $group_id $group_name
RUN useradd -s /bin/bash --uid $user_id \
    --gid $group_id -m $user_name
ARG home_dir=/home/$user_name
COPY rc $home_dir

RUN echo $user_name:$user_name | chpasswd
RUN echo $user_name ALL=\(root\) NOPASSWD:ALL \
    > /etc/sudoers.d/$user_name\
    && chmod 0440 /etc/sudoers.d/$user_name

RUN chown -R $user_name:$group_name $home_dir 
USER $user_name

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

